import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { AGENT_FILES, type Agent } from "./agent-files.js";

// Starter config. The linter's defaults already work, so this is mainly a discoverable place to set
// `lang`, a `tokens` path (enables token-binding), or per-rule `rules` overrides (error|warn|off).
const NORMARC = JSON.stringify({ lang: "en" }, null, 2) + "\n";

// A CI gate mirroring examples/ci-recipe.yml (Option A): fail on error-severity findings, plus a readable
// by-domain / by-rule summary in the Actions tab (rendered even when the gate above fails).
const WORKFLOW = `# Gate CI on the Norma design standard — fails on any error-severity finding; warnings are reported.
# Generated by \`norma-design-lint init\` — https://github.com/anhquanpbc/norma
name: Design lint (Norma)

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  norma:
    name: Norma design lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 22 }
      # The tool's own default extension set — includes jsx/tsx/vue/svelte components (narrow to your source, e.g. src/**).
      - run: npx norma-design-lint "**/*.{html,htm,css,jsx,tsx,vue,svelte}"
      - if: always()
        run: npx norma-design-lint "**/*.{html,htm,css,jsx,tsx,vue,svelte}" --format markdown >> "$GITHUB_STEP_SUMMARY" || true
`;

/** Project-level MCP client config for the norma-mcp server. `-p` runs the SECONDARY bin (the default bin
 *  is the linter), so `npx norma-design-lint norma-mcp` would run the linter, not the server. */
export const MCP_CONFIG =
  JSON.stringify({ mcpServers: { norma: { command: "npx", args: ["-y", "-p", "norma-design-lint", "norma-mcp"] } } }, null, 2) + "\n";

/** `--agent` selection: a single tool, or `all` (every per-tool file). AGENTS.md is always written. */
export type AgentSelector = "cursor" | "copilot" | "claude" | "all";

export interface ScaffoldResult { written: string[]; skipped: string[]; }

/**
 * Write the Norma starter files into `cwd`: a `.normarc.json`, a CI workflow, and the vendor-neutral
 * `AGENTS.md` rule file (from `agentsDir`, the bundled dist/agents). `agents` additionally installs the
 * rule file(s) for a specific tool (Cursor / Copilot / Claude Code) at their conventional paths; `mcp`
 * writes a `.mcp.json`. Existing files are skipped unless `force`. Pure over its inputs (all paths are
 * parameters) so it is testable against a temp dir.
 */
export function scaffold(opts: { cwd: string; agentsDir: string; force: boolean; agents?: AgentSelector; mcp?: boolean }): ScaffoldResult {
  const { cwd, agentsDir, force, agents, mcp } = opts;
  const written: string[] = [];
  const skipped: string[] = [];
  const put = (rel: string, content: string): void => {
    const abs = join(cwd, rel);
    if (existsSync(abs) && !force) { skipped.push(rel); return; }
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content);
    written.push(rel);
  };
  // Copy a bundled agent file (dist/agents/<dest>) to its adopter target; skip if the source isn't bundled.
  const putAgent = (f: (typeof AGENT_FILES)[number]): void => {
    const src = join(agentsDir, f.dest);
    if (existsSync(src)) put(f.target, readFileSync(src, "utf8"));
  };

  put(".normarc.json", NORMARC);
  put(".github/workflows/design-lint.yml", WORKFLOW);

  // AGENTS.md (vendor-neutral) is always installed; per-tool files only when `--agent` selects them.
  const wanted: Agent[] = agents ? (agents === "all" ? ["claude", "cursor", "copilot"] : [agents]) : [];
  for (const f of AGENT_FILES) {
    if (f.agent === "agents" || wanted.includes(f.agent)) putAgent(f);
  }

  if (mcp) put(".mcp.json", MCP_CONFIG);
  return { written, skipped };
}
