import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";

// Starter config. The linter's defaults already work, so this is mainly a discoverable place to set
// `lang`, a `tokens` path (enables token-binding), or per-rule `rules` overrides (error|warn|off).
const NORMARC = JSON.stringify({ lang: "en" }, null, 2) + "\n";

// A CI gate mirroring examples/ci-recipe.yml (Option A): fail on error-severity findings, plus a readable
// by-domain / by-rule summary in the Actions tab (rendered even when the gate above fails).
const WORKFLOW = `# Gate CI on the Norma design standard — fails on any error-severity finding; warnings are reported.
# Generated by \`norma-design-lint init\` — https://github.com/anhquanpbc/norma
name: Design lint (Norma)

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  norma:
    name: Norma design lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 22 }
      # The tool's own default extension set — includes jsx/tsx/vue/svelte components (narrow to your source, e.g. src/**).
      - run: npx norma-design-lint "**/*.{html,htm,css,jsx,tsx,vue,svelte}"
      - if: always()
        run: npx norma-design-lint "**/*.{html,htm,css,jsx,tsx,vue,svelte}" --format markdown >> "$GITHUB_STEP_SUMMARY" || true
`;

export interface ScaffoldResult { written: string[]; skipped: string[]; }

/**
 * Write the Norma starter files into `cwd`: a `.normarc.json`, a CI workflow, and the vendor-neutral
 * `AGENTS.md` rule file (copied from `agentsDir`, the bundled dist/agents). Existing files are skipped
 * unless `force`. Pure over its inputs (all paths are parameters) so it is testable against a temp dir.
 */
export function scaffold(opts: { cwd: string; agentsDir: string; force: boolean }): ScaffoldResult {
  const { cwd, agentsDir, force } = opts;
  const written: string[] = [];
  const skipped: string[] = [];
  const put = (rel: string, content: string): void => {
    const abs = join(cwd, rel);
    if (existsSync(abs) && !force) { skipped.push(rel); return; }
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content);
    written.push(rel);
  };
  put(".normarc.json", NORMARC);
  put(".github/workflows/design-lint.yml", WORKFLOW);
  const agentsSrc = join(agentsDir, "AGENTS.md");
  if (existsSync(agentsSrc)) put("AGENTS.md", readFileSync(agentsSrc, "utf8"));
  return { written, skipped };
}
