/**
 * gen-agents.ts — project the ONE canonical agent spec + the rule catalog into every
 * AI-surface rule file, so a change in agents/norma-design-agent.md or standard/rules.yaml
 * updates all surfaces from a single edit. Never hand-edit the generated files.
 *
 *   agents/norma-design-agent.md  +  standard/rules.json
 *        │
 *        ├──▶ .claude/agents/design-guardian.md      (Claude Code subagent)
 *        ├──▶ .cursor/rules/norma-design.mdc         (Cursor project rule)
 *        ├──▶ .github/copilot-instructions.md        (GitHub Copilot)
 *        ├──▶ .github/instructions/css.instructions.md   (Copilot, applyTo CSS)
 *        ├──▶ .github/instructions/html.instructions.md  (Copilot, applyTo HTML)
 *        ├──▶ AGENTS.md                              (vendor-neutral)
 *        └──▶ CLAUDE.md                              (Claude Code project memory)
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { onSurface } from "../packages/design-lint/src/surfaces.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

type Rule = {
  id: string; tag: "SPEC" | "CONV"; severity: string;
  title: { en: string; vi: string }; source: string; source_url?: string;
  check: { type: string };
};
const catalog = JSON.parse(readFileSync(join(root, "standard/rules.json"), "utf8")) as { version: string; rules: Rule[] };

const canonical = readFileSync(join(root, "agents/norma-design-agent.md"), "utf8");
const body = canonical.slice(canonical.indexOf("## Role")).trim();

const BANNER = "<!-- GENERATED by scripts/gen-agents.ts from agents/norma-design-agent.md + standard/rules.json. Do not edit; run `npm run gen`. -->";

function ruleLine(r: Rule): string {
  const badge = r.tag === "SPEC" ? "🔒 SPEC" : "📐 CONV";
  const src = r.source_url ? `[${r.source}](${r.source_url})` : r.source;
  // check:manual rules are engine-skipped — mark them so the greppable index can't be mistaken
  // for a linted rule of the same severity.
  const sev = r.check.type === "manual" ? `${r.severity} · manual, agent-verified` : r.severity;
  return `- ${badge} \`${r.id}\` (${sev}) — ${r.title.en} · ${src}`;
}
function ruleIndex(filter: (r: Rule) => boolean = () => true, heading = `Rule index (generated from standard/rules.json v${catalog.version})`): string {
  return `## ${heading}\n\n${catalog.rules.filter(filter).map(ruleLine).join("\n")}\n`;
}

function write(rel: string, content: string) {
  const abs = join(root, rel);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content.replace(/\n{3,}/g, "\n\n").trimEnd() + "\n");
  console.log(`✓ ${rel}`);
}

// 1. Claude Code subagent
write(".claude/agents/design-guardian.md", `---
name: design-guardian
description: Reviews and generates web UI against the Norma design standard. Use proactively after any HTML, CSS, or component change.
tools: Read, Grep, Glob, Bash
model: inherit
---
${BANNER}

# Norma Design Guardian

${body}

${ruleIndex()}`);

// 2. Cursor project rule
write(".cursor/rules/norma-design.mdc", `---
description: Norma web design standard — accessible-by-construction, tokenized, no AI tells.
globs: **/*.{html,css,tsx,jsx,vue,svelte,astro}
alwaysApply: false
---
${BANNER}

${body}

${ruleIndex()}`);

// 3. Copilot repo-wide instructions
write(".github/copilot-instructions.md", `${BANNER}

# Norma design standard

${body}

${ruleIndex()}`);

// 4. Copilot scoped — CSS
write(".github/instructions/css.instructions.md", `---
applyTo: "**/*.{css,scss}"
---
${BANNER}

# Norma — CSS/styling rules

Use tokens from \`standard/tokens.tokens.json\`. Color and spacing come from tokens only; one clean
\`:focus-visible\` ring; honor \`prefers-reduced-motion\`; no indigo default; no pure black/white dark mode.

${ruleIndex((r) => onSurface(r.check.type, "css"), "Applicable rules")}`);

// 5. Copilot scoped — HTML
write(".github/instructions/html.instructions.md", `---
applyTo: "**/*.{html,htm,jsx,tsx,vue,svelte}"
---
${BANNER}

# Norma — HTML/markup rules

Semantic HTML first: interactive controls are \`<button>\`/\`<a>\`, never \`<div onClick>\`. Every input has a
real \`<label>\`. Touch targets ≥ 24 CSS px. Set \`width\`/\`height\` on images. No emoji as icons.

${ruleIndex((r) => onSurface(r.check.type, "html"), "Applicable rules")}`);

// 6. Vendor-neutral AGENTS.md
write("AGENTS.md", `${BANNER}

# Norma — design standard for agents

This repository defines the **Norma** web design standard. Any agent editing UI here (or in a project
that adopts Norma) must follow the rules below. The authoritative catalog is \`standard/rules.json\`
(compiled from \`standard/rules.yaml\`); design tokens are in \`standard/tokens.tokens.json\`.

## The six pillars

Norma is comprehensive *control* over design quality — the rules below are enforced by real tooling, so
you can (and should) self-check your output with the linter:

| Pillar | What it does | How Norma ships it |
|--------|--------------|--------------------|
| **Define** | one source of truth | \`standard/rules.yaml\` + DTCG tokens (\`tokens.tokens.json\`) |
| **Enforce** | fail the build on violations | the \`norma-design-lint\` CLI + Stylelint (\`norma-design-lint/stylelint\`) & ESLint (\`norma-design-lint/eslint\`) plugins |
| **Generate** | derive every consumer artifact | these agent rule files, a zero-dependency MCP server, and compiled CSS vars (\`standard/tokens.css\`) |
| **Govern** | deliver findings where teams work | enriched SARIF 2.1.0 → GitHub code scanning |
| **Sync** | adopt & stay in step, no drift | a \`--baseline\` ratchet, a DTCG token validator (\`tokens validate\`), and anti-drift guards |
| **Measure** | see the state of each run | a Markdown run summary (\`--format markdown\`) + code-scanning trends |

${body}

${ruleIndex()}

## How to verify

\`\`\`
npx norma-design-lint "**/*.{html,css}"
\`\`\`
Exits non-zero on any \`error\`-severity finding. Also do a manual keyboard + screen-reader pass.`);

// 7. Claude Code project memory
write("CLAUDE.md", `${BANNER}

# Norma

This repo defines the **Norma** web design standard (a reference for humans and AI).

- Design rules: \`standard/rules.yaml\` → \`standard/rules.json\`. Tokens: \`standard/tokens.tokens.json\`.
- Agent behaviour: follow \`AGENTS.md\` (generated from \`agents/norma-design-agent.md\`).
- Before committing UI changes, run \`npm run lint:self\` and \`npm run check:drift\`.
- To change a rule: edit \`standard/rules.yaml\` (or \`agents/norma-design-agent.md\`), then \`npm run build:rules && npm run gen\`. Never hand-edit generated files.`);

console.log(`\nGenerated ${catalog.rules.length} rules into 7 surface files.`);
